version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    container_name: mongo_maklerplus
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=maklerplus
    volumes:
      - ./init/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro